# Generated by Django 5.2.15 on 2026-06-28 07:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0007_resume_completion_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('keyword_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('industry_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('completion_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ats_histories', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ATS History',
                'verbose_name_plural': 'ATS Histories',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareerProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('career_score', models.FloatField(default=0.0)),
                ('growth_score', models.FloatField(default=0.0)),
                ('learning_score', models.FloatField(default=0.0)),
                ('industry_match', models.JSONField(blank=True, default=dict)),
                ('market_alignment', models.FloatField(default=0.0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Progress',
                'verbose_name_plural': 'Career Progress entries',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('topic', models.CharField(max_length=255)),
                ('source', models.CharField(default='System', max_length=100)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning History',
                'verbose_name_plural': 'Learning Histories',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Snapshot',
                'verbose_name_plural': 'Profile Snapshots',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('version_number', models.IntegerField(default=1)),
                ('ats_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('completion_score', models.FloatField(default=0.0)),
                ('profile_snapshot', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, default='')),
                ('change_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume Version',
                'verbose_name_plural': 'Resume Versions',
                'ordering': ['-version_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('skill_name', models.CharField(max_length=100)),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('removed_date', models.DateField(blank=True, null=True)),
                ('skill_category', models.CharField(default='General', max_length=50)),
                ('source', models.CharField(default='Manual', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill History',
                'verbose_name_plural': 'Skill Histories',
                'ordering': ['-added_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('event_type', models.CharField(choices=[('resume_uploaded', 'Resume Uploaded'), ('resume_updated', 'Resume Updated'), ('ats_improved', 'ATS Improved'), ('skill_added', 'Skill Added'), ('skill_removed', 'Skill Removed'), ('project_added', 'Project Added'), ('experience_added', 'Experience Added'), ('certificate_added', 'Certificate Added'), ('portfolio_published', 'Portfolio Published'), ('portfolio_updated', 'Portfolio Updated'), ('cover_letter_generated', 'Cover Letter Generated'), ('career_roadmap_started', 'Career Roadmap Started'), ('roadmap_completed', 'Roadmap Completed'), ('resume_generated', 'Resume Generated'), ('resume_downloaded', 'Resume Downloaded'), ('theme_changed', 'Theme Changed')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
