# Generated by Django 5.2.15 on 2026-06-26 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('resume_title', models.CharField(db_index=True, help_text="A descriptive title, e.g. 'Software Engineer – 2025'", max_length=255, verbose_name='Resume Title')),
                ('original_file', models.FileField(help_text='Accepted formats: PDF, DOCX', upload_to='resumes/%Y/%m/', verbose_name='Original File')),
                ('extracted_text', models.TextField(blank=True, help_text='Raw text extracted from the uploaded file.', verbose_name='Extracted Text')),
                ('parsed_json', models.JSONField(blank=True, help_text='Structured data extracted by the AI parser.', null=True, verbose_name='Parsed JSON')),
                ('parsing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Parsing Status')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-upload_date'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'parsing_status'], name='idx_resume_user_status')],
            },
        ),
    ]
