# Generated by Django 5.2.15 on 2026-06-26 09:33

import apps.resumes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='File Size (bytes)'),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='resume',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='MIME Type'),
        ),
        migrations.AddField(
            model_name='resume',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Original Filename'),
        ),
        migrations.AddField(
            model_name='resume',
            name='stored_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stored Filename'),
        ),
        migrations.AddField(
            model_name='resume',
            name='upload_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20, verbose_name='Upload Status'),
        ),
        migrations.AddField(
            model_name='resume',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='original_file',
            field=models.FileField(help_text='Accepted formats: PDF, DOCX', upload_to=apps.resumes.models.resume_upload_path, verbose_name='Original File'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'is_active'], name='idx_resume_user_active'),
        ),
    ]
