# Generated by Django 5.2.15 on 2026-06-26 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_file_size_resume_is_active_resume_mime_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='resume',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Extraction Status'),
        ),
        migrations.AddField(
            model_name='resume',
            name='extraction_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Extraction Time'),
        ),
        migrations.AddField(
            model_name='resume',
            name='processing_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Processing Duration (seconds)'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'extraction_status'], name='idx_resume_user_extract'),
        ),
    ]
