# Generated by Django 5.2.15 on 2026-06-26 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_error_message_resume_extraction_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='regex_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Regex Completed At'),
        ),
        migrations.AddField(
            model_name='resume',
            name='regex_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Regex Extracted JSON'),
        ),
        migrations.AddField(
            model_name='resume',
            name='regex_processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Regex Processing Time (seconds)'),
        ),
        migrations.AddField(
            model_name='resume',
            name='regex_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Regex Status'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'regex_status'], name='idx_resume_user_regex'),
        ),
    ]
