# Generated by Django 5.2.15 on 2026-06-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_regex_completed_at_resume_regex_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='spacy_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='spaCy Completed At'),
        ),
        migrations.AddField(
            model_name='resume',
            name='spacy_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='spaCy Extracted JSON'),
        ),
        migrations.AddField(
            model_name='resume',
            name='spacy_processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='spaCy Processing Time (seconds)'),
        ),
        migrations.AddField(
            model_name='resume',
            name='spacy_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='spaCy Status'),
        ),
    ]
