# Generated by Django 5.2.15 on 2026-06-26 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_spacy_completed_at_resume_spacy_json_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI Completed At'),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='AI Extracted JSON'),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='AI Model Used'),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='AI Processing Time (seconds)'),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_prompt_version',
            field=models.CharField(blank=True, default='v1', max_length=50, verbose_name='AI Prompt Version'),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='AI Status'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'ai_status'], name='idx_resume_user_ai'),
        ),
    ]
