# Generated by Django 5.2.15 on 2026-06-26 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resume_ai_completed_at_resume_ai_json_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='completion_percentage',
            field=models.FloatField(default=0.0, verbose_name='Completion Percentage'),
        ),
        migrations.AddField(
            model_name='resume',
            name='master_resume_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Master Resume JSON'),
        ),
        migrations.AddField(
            model_name='resume',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Validation Status'),
        ),
        migrations.AddField(
            model_name='resume',
            name='validation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validation Time'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'validation_status'], name='idx_resume_user_validation'),
        ),
    ]
