# Generated by Django 5.2.15 on 2026-07-04 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_resume_completion_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(help_text='Normalized section type (e.g. experience, education, skills)', max_length=50, verbose_name='Normalized Section Type')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Original Section Title')),
                ('confidence', models.FloatField(default=100.0, verbose_name='Confidence Score (0-100)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position Index')),
                ('page', models.PositiveIntegerField(default=1, verbose_name='Page Number')),
                ('content', models.TextField(blank=True, default='', verbose_name='Section Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Resume Section',
                'verbose_name_plural': 'Resume Sections',
                'ordering': ['position'],
            },
        ),
    ]
