# Generated by Django 5.2.15 on 2026-07-04 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_resumesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidenceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(help_text='Name of the parsed field (e.g. name, email, phone)', max_length=100, verbose_name='Field Name')),
                ('value', models.TextField(blank=True, default='', verbose_name='Extracted Value')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Confidence Score (0-100)')),
                ('source', models.CharField(help_text='Primary extraction source (e.g. regex, spacy, gemini, manual)', max_length=50, verbose_name='Extraction Source')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Scoring Rationale')),
                ('status', models.CharField(help_text='Status based on confidence limits (e.g. accepted, review, warning, rejected)', max_length=30, verbose_name='Calibration Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_scores', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Confidence Score',
                'verbose_name_plural': 'Confidence Scores',
                'ordering': ['field'],
            },
        ),
    ]
