# Generated by Django 5.2.15 on 2026-07-05 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_confidencescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(help_text='Extracted field key or sub-key', max_length=100, verbose_name='Field Name')),
                ('value', models.TextField(blank=True, default='', verbose_name='Extracted Value')),
                ('category', models.CharField(help_text='Semantic category detected by ontology/classifier (e.g. University)', max_length=50, verbose_name='Detected Category')),
                ('expected_category', models.CharField(blank=True, default='', help_text='Category expected based on resume section (e.g. Skill)', max_length=50, verbose_name='Expected Category')),
                ('semantic_score', models.FloatField(default=0.0, verbose_name='Semantic Score (0-100)')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Semantic Explanation')),
                ('status', models.CharField(help_text='valid (90+), possible (75-90), suspicious (50-75), invalid (<50)', max_length=30, verbose_name='Validation Status')),
                ('action', models.CharField(help_text='accept, review, recover, move, move_to_<category>, reject', max_length=50, verbose_name='Action Flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_validations', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Semantic Validation',
                'verbose_name_plural': 'Semantic Validations',
                'ordering': ['-semantic_score', 'field'],
            },
        ),
    ]
