# Generated by Django 5.2.15 on 2026-07-05 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_semanticvalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='wrong_entity, timeline_error, duplicate_value, missing_contact, etc.', max_length=50, verbose_name='Error Type')),
                ('field', models.CharField(max_length=100, verbose_name='Field / Target')),
                ('value', models.TextField(blank=True, default='', verbose_name='Extracted Value')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20, verbose_name='Severity Level')),
                ('confidence', models.FloatField(default=100.0, verbose_name='Detection Confidence (0-100)')),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('review', 'Review'), ('recover', 'Recover'), ('ignore', 'Ignore'), ('move', 'Move'), ('reject', 'Reject')], default='review', max_length=50, verbose_name='Recommended Action')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Error Explanation / Rationale')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_detections', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Resume Error',
                'verbose_name_plural': 'Resume Errors',
                'ordering': ['-created_at', 'severity', 'field'],
            },
        ),
    ]
