# Generated by Django 5.2.15 on 2026-07-05 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_resumeerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='Field / Section')),
                ('previous_value', models.TextField(blank=True, default='', verbose_name='Previous Value')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='Recovered Value')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Recovery Explanation')),
                ('confidence', models.FloatField(default=100.0, verbose_name='Recovery Confidence (0-100)')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('reviewed', 'Reviewed'), ('recovered', 'Recovered'), ('suggested', 'Suggested'), ('manual', 'Manual'), ('rejected', 'Rejected')], default='recovered', help_text='accepted, reviewed, recovered, suggested, manual, rejected', max_length=50, verbose_name='Recovery Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_logs', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Recovery Log',
                'verbose_name_plural': 'Recovery Logs',
                'ordering': ['-created_at', 'field'],
            },
        ),
    ]
