# Generated by Django 5.2.15 on 2026-07-05 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0012_recoverylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsistencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=100.0, verbose_name='Consistency Score (0-100)')),
                ('score_label', models.CharField(default='Excellent', help_text='Excellent, Strong, Average, Weak, Needs Review', max_length=50, verbose_name='Score Label')),
                ('issues', models.JSONField(blank=True, default=list, verbose_name='Detected Consistency Issues')),
                ('suggestions', models.JSONField(blank=True, default=list, verbose_name='Recommended Skill & Profile Actions')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='Consistency Metrics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_reports', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Consistency Report',
                'verbose_name_plural': 'Consistency Reports',
                'ordering': ['-created_at', '-score'],
            },
        ),
    ]
