# Generated by Django 5.2.15 on 2026-07-05 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0013_consistencyreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255, verbose_name='Field Name')),
                ('previous_value', models.TextField(blank=True, default='', verbose_name='Previous Value')),
                ('current_value', models.TextField(blank=True, default='', verbose_name='Current Value')),
                ('source', models.CharField(default='User Edit', max_length=100, verbose_name='Source / Engine')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Modification Reason')),
                ('confidence', models.FloatField(default=100.0, verbose_name='Confidence Score (0-100)')),
                ('version', models.IntegerField(default=1, verbose_name='Resume Version Number')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_histories', to='resumes.resume', verbose_name='Resume')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_history_edits', to=settings.AUTH_USER_MODEL, verbose_name='Modified By User')),
            ],
            options={
                'verbose_name': 'Field History Log',
                'verbose_name_plural': 'Field History Logs',
                'ordering': ['-timestamp', 'field'],
            },
        ),
        migrations.CreateModel(
            name='FieldSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255, verbose_name='Field Name')),
                ('value', models.TextField(blank=True, default='', verbose_name='Field Value')),
                ('source', models.CharField(default='spacy', help_text='regex, spacy, gemini, section_detector, semantic_validator, recovery_engine, consistency_checker, user_edit, manual', max_length=100, verbose_name='Source Origin')),
                ('confidence', models.FloatField(default=100.0, verbose_name='Confidence Score (0-100)')),
                ('status', models.CharField(default='extracted', help_text='extracted, inferred, corrected, generated, recovered, edited, approved, imported, manual', max_length=50, verbose_name='Provenance Status')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Source Reason / Explanation')),
                ('ui_color', models.CharField(default='#3B82F6', max_length=50, verbose_name='UI Highlight Color')),
                ('version', models.IntegerField(default=1, verbose_name='Version Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_sources', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Field Source',
                'verbose_name_plural': 'Field Sources',
                'ordering': ['resume', 'field'],
                'unique_together': {('resume', 'field', 'version')},
            },
        ),
    ]
