# Generated by Django 5.2.15 on 2026-07-05 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0014_fieldhistory_fieldsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfHealingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=95.0, verbose_name='Final Confidence Score')),
                ('issues_found', models.IntegerField(default=0, verbose_name='Issues Found')),
                ('issues_fixed', models.IntegerField(default=0, verbose_name='Issues Fixed')),
                ('needs_review', models.IntegerField(default=0, verbose_name='Needs Review Count')),
                ('recovered_fields_count', models.IntegerField(default=0, verbose_name='Recovered Fields Count')),
                ('decision', models.CharField(default='accept', help_text='accept, review, recover, reject, escalate', max_length=50, verbose_name='Decision Status')),
                ('approval_tier', models.CharField(default='auto_approve', help_text='auto_approve, approve, ask_confirmation, manual_verification', max_length=50, verbose_name='Approval Tier')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Healing Summary')),
                ('master_resume_output', models.JSONField(blank=True, default=dict, verbose_name='Master Resume JSON Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_healing_reports', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Self Healing Report',
                'verbose_name_plural': 'Self Healing Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
