# Generated by Django 5.2.15 on 2026-07-05 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0015_selfhealingreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='add_skill, remove_skill, update_education, improve_summary, etc.', max_length=100, verbose_name='Action Type')),
                ('previous_state', models.JSONField(blank=True, default=dict, verbose_name='Previous State Snapshot')),
                ('new_state', models.JSONField(blank=True, default=dict, verbose_name='New State Snapshot')),
                ('confidence', models.FloatField(default=95.0, verbose_name='Action Confidence')),
                ('is_undone', models.BooleanField(default=False, verbose_name='Is Undone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_actions', to='resumes.resume', verbose_name='Resume')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copilot_actions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Copilot Action Log',
                'verbose_name_plural': 'Copilot Action Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CopilotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='User Message')),
                ('response', models.TextField(verbose_name='Copilot Response')),
                ('intent', models.CharField(default='chat', max_length=100, verbose_name='Classified Intent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copilot_conversations', to='resumes.resume', verbose_name='Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_conversations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Copilot Conversation',
                'verbose_name_plural': 'Copilot Conversations',
                'ordering': ['-created_at'],
            },
        ),
    ]
