"""
ATS models – Applicant Tracking System scoring.

Stores ATS analysis results for each resume including
overall score, detailed json data, processing details, and suggestions.
"""

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from apps.common.models import BaseModel
from apps.resumes.models import Resume


class ATSScore(BaseModel):
    """
    ATS analysis result for a resume.

    Foreign key with Resume to support analysis history.
    """

    resume = models.ForeignKey(
        Resume,
        on_delete=models.CASCADE,
        related_name="ats_analyses",
        verbose_name="Resume",
    )
    ats_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        verbose_name="Overall ATS Score",
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text="Overall ATS compatibility score (0-100).",
    )
    ats_json = models.JSONField(
        verbose_name="ATS Analysis JSON",
        help_text="Detailed JSON containing all sub-scores, keyword analyses, grammar notes, and stats.",
    )
    ats_completed_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Completed At",
    )
    ats_processing_time = models.FloatField(
        verbose_name="Processing Time (Seconds)",
        help_text="Time taken to perform the ATS analysis in seconds.",
    )
    industry_match = models.JSONField(
        verbose_name="Industry Matches",
        help_text="List/dict of industry match percentages.",
    )
    missing_skills = models.JSONField(
        verbose_name="Missing Skills",
        help_text="Suggested skills based on detected primary industry.",
    )
    suggestions = models.JSONField(
        verbose_name="Suggestions",
        help_text="Actionable suggestions categorized by priority.",
    )

    class Meta(BaseModel.Meta):
        verbose_name = "ATS Score"
        verbose_name_plural = "ATS Scores"
        ordering = ["-ats_completed_at"]

    def __str__(self):
        return f"ATS {self.ats_score}/100 – {self.resume.resume_title} (Completed: {self.ats_completed_at})"


class ATSReport(BaseModel):
    """
    Detailed ATS report generated by the ATS Intelligence Engine.
    Supports both Generic and Job-Specific modes.
    """
    resume = models.ForeignKey(
        Resume,
        on_delete=models.CASCADE,
        related_name="ats_reports",
        verbose_name="Resume"
    )
    overall_score = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Overall ATS Score"
    )
    confidence = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Confidence Score"
    )
    job_ready = models.BooleanField(
        default=False,
        verbose_name="Job Ready Status"
    )
    parsing_quality = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Parsing Quality"
    )
    strengths = models.JSONField(
        default=list,
        verbose_name="Strengths List"
    )
    weaknesses = models.JSONField(
        default=list,
        verbose_name="Weaknesses List"
    )
    recommendations = models.JSONField(
        default=list,
        verbose_name="Recommendations"
    )
    subscores = models.JSONField(
        default=dict,
        verbose_name="Sub-scores Breakdown"
    )
    job_description_text = models.TextField(
        null=True,
        blank=True,
        verbose_name="Target Job Description"
    )
    metadata = models.JSONField(
        default=dict,
        verbose_name="Metadata"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Created At"
    )

    class Meta(BaseModel.Meta):
        verbose_name = "ATS Report"
        verbose_name_plural = "ATS Reports"
        ordering = ["-created_at"]

    def __str__(self):
        mode = "Job-Specific" if self.job_description_text else "Generic"
        return f"ATS Report {self.overall_score}/100 – {self.resume.resume_title} ({mode})"


class ATSBenchmark(BaseModel):
    """
    Profession-specific benchmarks and percentiles for ATS scoring.
    """
    profession = models.CharField(
        max_length=100,
        unique=True,
        verbose_name="Profession/Role Name"
    )
    percentile_25 = models.IntegerField(default=55)
    percentile_50 = models.IntegerField(default=70)
    percentile_75 = models.IntegerField(default=82)
    percentile_90 = models.IntegerField(default=92)
    average_score = models.IntegerField(default=68)

    class Meta(BaseModel.Meta):
        verbose_name = "ATS Benchmark"
        verbose_name_plural = "ATS Benchmarks"

    def __str__(self):
        return f"Benchmark for {self.profession}"


class ATSRecommendation(BaseModel):
    """
    Pre-configured library of ATS suggestions and potential score boosts.
    """
    category = models.CharField(
        max_length=100,
        verbose_name="Category"
    )
    suggestion = models.TextField(
        verbose_name="Actionable Suggestion"
    )
    priority = models.CharField(
        max_length=20,
        choices=[("critical", "Critical"), ("important", "Important"), ("optional", "Optional")],
        default="important"
    )
    potential_boost = models.IntegerField(
        default=5,
        verbose_name="Potential Score Boost"
    )

    class Meta(BaseModel.Meta):
        verbose_name = "ATS Recommendation"
        verbose_name_plural = "ATS Recommendations"

    def __str__(self):
        return f"[{self.category}] {self.suggestion[:50]}..."


class ATSHistory(BaseModel):
    """
    Historical log of ATS runs for tracking score improvement over time.
    """
    resume = models.ForeignKey(
        Resume,
        on_delete=models.CASCADE,
        related_name="ats_history_logs",
        verbose_name="Resume"
    )
    overall_score = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Overall Score"
    )
    report = models.ForeignKey(
        ATSReport,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="history_links",
        verbose_name="Linked Report"
    )
    completed_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Completed At"
    )

    class Meta(BaseModel.Meta):
        verbose_name = "ATS History Log"
        verbose_name_plural = "ATS History Logs"
        ordering = ["-completed_at"]

    def __str__(self):
        return f"History Log: {self.overall_score}/100 for {self.resume.resume_title} at {self.completed_at}"


class RuleCategory(BaseModel):
    name = models.CharField(max_length=100, unique=True, verbose_name="Category Name")
    description = models.TextField(blank=True, null=True, verbose_name="Description")
    weight = models.FloatField(default=1.0, verbose_name="Category Weight")

    class Meta(BaseModel.Meta):
        verbose_name = "Rule Category"
        verbose_name_plural = "Rule Categories"
        ordering = ["name"]

    def __str__(self):
        return self.name


class ATSRule(BaseModel):
    rule_code = models.CharField(max_length=100, unique=True, verbose_name="Rule Code")
    name = models.CharField(max_length=255, verbose_name="Rule Name")
    category = models.ForeignKey(RuleCategory, on_delete=models.CASCADE, related_name="rules", verbose_name="Category")
    description = models.TextField(verbose_name="Rule Description")
    condition = models.TextField(verbose_name="Condition (Python Expression)")
    points = models.IntegerField(default=0, verbose_name="Points / Score Impact")
    severity = models.CharField(
        max_length=20,
        choices=[("critical", "Critical"), ("high", "High"), ("medium", "Medium"), ("low", "Low")],
        default="medium"
    )
    profession = models.CharField(max_length=100, default="All", verbose_name="Target Profession")
    enabled = models.BooleanField(default=True, verbose_name="Enabled")
    recommendation = models.TextField(verbose_name="Recommendation on Failure")
    explanation = models.TextField(verbose_name="Explanation / Logic")

    class Meta(BaseModel.Meta):
        verbose_name = "ATS Rule"
        verbose_name_plural = "ATS Rules"
        ordering = ["rule_code"]

    def __str__(self):
        return f"[{self.rule_code}] {self.name}"


class RuleExecution(BaseModel):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name="rule_executions", verbose_name="Resume")
    rule = models.ForeignKey(ATSRule, on_delete=models.CASCADE, related_name="executions", verbose_name="Rule")
    status = models.CharField(
        max_length=20,
        choices=[("passed", "Passed"), ("failed", "Failed"), ("skipped", "Skipped")],
        default="skipped"
    )
    score_impact = models.IntegerField(default=0, verbose_name="Score Impact")
    reason = models.TextField(blank=True, null=True, verbose_name="Execution Reason / Explanation")
    recommendation = models.TextField(blank=True, null=True, verbose_name="Actionable Recommendation")
    executed_at = models.DateTimeField(auto_now_add=True, verbose_name="Executed At")

    class Meta(BaseModel.Meta):
        verbose_name = "Rule Execution"
        verbose_name_plural = "Rule Executions"
        ordering = ["-executed_at"]

    def __str__(self):
        return f"Execution of {self.rule.rule_code} on {self.resume.resume_title}: {self.status}"


