"""
ATS models – Applicant Tracking System scoring.

Stores ATS analysis results for each resume including
overall score, detailed json data, processing details, and suggestions.
"""

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from apps.common.models import BaseModel
from apps.resumes.models import Resume


class ATSScore(BaseModel):
    """
    ATS analysis result for a resume.

    Foreign key with Resume to support analysis history.
    """

    resume = models.ForeignKey(
        Resume,
        on_delete=models.CASCADE,
        related_name="ats_analyses",
        verbose_name="Resume",
    )
    ats_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        verbose_name="Overall ATS Score",
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text="Overall ATS compatibility score (0-100).",
    )
    ats_json = models.JSONField(
        verbose_name="ATS Analysis JSON",
        help_text="Detailed JSON containing all sub-scores, keyword analyses, grammar notes, and stats.",
    )
    ats_completed_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Completed At",
    )
    ats_processing_time = models.FloatField(
        verbose_name="Processing Time (Seconds)",
        help_text="Time taken to perform the ATS analysis in seconds.",
    )
    industry_match = models.JSONField(
        verbose_name="Industry Matches",
        help_text="List/dict of industry match percentages.",
    )
    missing_skills = models.JSONField(
        verbose_name="Missing Skills",
        help_text="Suggested skills based on detected primary industry.",
    )
    suggestions = models.JSONField(
        verbose_name="Suggestions",
        help_text="Actionable suggestions categorized by priority.",
    )

    class Meta(BaseModel.Meta):
        verbose_name = "ATS Score"
        verbose_name_plural = "ATS Scores"
        ordering = ["-ats_completed_at"]

    def __str__(self):
        return f"ATS {self.ats_score}/100 – {self.resume.resume_title} (Completed: {self.ats_completed_at})"


class ATSReport(BaseModel):
    """
    Detailed ATS report generated by the ATS Intelligence Engine.
    Supports both Generic and Job-Specific modes.
    """
    resume = models.ForeignKey(
        Resume,
        on_delete=models.CASCADE,
        related_name="ats_reports",
        verbose_name="Resume"
    )
    overall_score = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Overall ATS Score"
    )
    confidence = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Confidence Score"
    )
    job_ready = models.BooleanField(
        default=False,
        verbose_name="Job Ready Status"
    )
    parsing_quality = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Parsing Quality"
    )
    strengths = models.JSONField(
        default=list,
        verbose_name="Strengths List"
    )
    weaknesses = models.JSONField(
        default=list,
        verbose_name="Weaknesses List"
    )
    recommendations = models.JSONField(
        default=list,
        verbose_name="Recommendations"
    )
    subscores = models.JSONField(
        default=dict,
        verbose_name="Sub-scores Breakdown"
    )
    job_description_text = models.TextField(
        null=True,
        blank=True,
        verbose_name="Target Job Description"
    )
    metadata = models.JSONField(
        default=dict,
        verbose_name="Metadata"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Created At"
    )

    class Meta(BaseModel.Meta):
        verbose_name = "ATS Report"
        verbose_name_plural = "ATS Reports"
        ordering = ["-created_at"]

    def __str__(self):
        mode = "Job-Specific" if self.job_description_text else "Generic"
        return f"ATS Report {self.overall_score}/100 – {self.resume.resume_title} ({mode})"


class ATSBenchmark(BaseModel):
    """
    Profession-specific benchmarks and percentiles for ATS scoring.
    """
    profession = models.CharField(
        max_length=100,
        unique=True,
        verbose_name="Profession/Role Name"
    )
    percentile_25 = models.IntegerField(default=55)
    percentile_50 = models.IntegerField(default=70)
    percentile_75 = models.IntegerField(default=82)
    percentile_90 = models.IntegerField(default=92)
    average_score = models.IntegerField(default=68)

    class Meta(BaseModel.Meta):
        verbose_name = "ATS Benchmark"
        verbose_name_plural = "ATS Benchmarks"

    def __str__(self):
        return f"Benchmark for {self.profession}"


class ATSRecommendation(BaseModel):
    """
    Pre-configured library of ATS suggestions and potential score boosts.
    """
    category = models.CharField(
        max_length=100,
        verbose_name="Category"
    )
    suggestion = models.TextField(
        verbose_name="Actionable Suggestion"
    )
    priority = models.CharField(
        max_length=20,
        choices=[("critical", "Critical"), ("important", "Important"), ("optional", "Optional")],
        default="important"
    )
    potential_boost = models.IntegerField(
        default=5,
        verbose_name="Potential Score Boost"
    )

    class Meta(BaseModel.Meta):
        verbose_name = "ATS Recommendation"
        verbose_name_plural = "ATS Recommendations"

    def __str__(self):
        return f"[{self.category}] {self.suggestion[:50]}..."


class ATSHistory(BaseModel):
    """
    Historical log of ATS runs for tracking score improvement over time.
    """
    resume = models.ForeignKey(
        Resume,
        on_delete=models.CASCADE,
        related_name="ats_history_logs",
        verbose_name="Resume"
    )
    overall_score = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Overall Score"
    )
    report = models.ForeignKey(
        ATSReport,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="history_links",
        verbose_name="Linked Report"
    )
    completed_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Completed At"
    )

    class Meta(BaseModel.Meta):
        verbose_name = "ATS History Log"
        verbose_name_plural = "ATS History Logs"
        ordering = ["-completed_at"]

    def __str__(self):
        return f"History Log: {self.overall_score}/100 for {self.resume.resume_title} at {self.completed_at}"


class RuleCategory(BaseModel):
    name = models.CharField(max_length=100, unique=True, verbose_name="Category Name")
    description = models.TextField(blank=True, null=True, verbose_name="Description")
    weight = models.FloatField(default=1.0, verbose_name="Category Weight")

    class Meta(BaseModel.Meta):
        verbose_name = "Rule Category"
        verbose_name_plural = "Rule Categories"
        ordering = ["name"]

    def __str__(self):
        return self.name


class ATSRule(BaseModel):
    rule_code = models.CharField(max_length=100, unique=True, verbose_name="Rule Code")
    name = models.CharField(max_length=255, verbose_name="Rule Name")
    category = models.ForeignKey(RuleCategory, on_delete=models.CASCADE, related_name="rules", verbose_name="Category")
    description = models.TextField(verbose_name="Rule Description")
    condition = models.TextField(verbose_name="Condition (Python Expression)")
    points = models.IntegerField(default=0, verbose_name="Points / Score Impact")
    severity = models.CharField(
        max_length=20,
        choices=[("critical", "Critical"), ("high", "High"), ("medium", "Medium"), ("low", "Low")],
        default="medium"
    )
    profession = models.CharField(max_length=100, default="All", verbose_name="Target Profession")
    enabled = models.BooleanField(default=True, verbose_name="Enabled")
    recommendation = models.TextField(verbose_name="Recommendation on Failure")
    explanation = models.TextField(verbose_name="Explanation / Logic")

    class Meta(BaseModel.Meta):
        verbose_name = "ATS Rule"
        verbose_name_plural = "ATS Rules"
        ordering = ["rule_code"]

    def __str__(self):
        return f"[{self.rule_code}] {self.name}"


class RuleExecution(BaseModel):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name="rule_executions", verbose_name="Resume")
    rule = models.ForeignKey(ATSRule, on_delete=models.CASCADE, related_name="executions", verbose_name="Rule")
    status = models.CharField(
        max_length=20,
        choices=[("passed", "Passed"), ("failed", "Failed"), ("skipped", "Skipped")],
        default="skipped"
    )
    score_impact = models.IntegerField(default=0, verbose_name="Score Impact")
    reason = models.TextField(blank=True, null=True, verbose_name="Execution Reason / Explanation")
    recommendation = models.TextField(blank=True, null=True, verbose_name="Actionable Recommendation")
    executed_at = models.DateTimeField(auto_now_add=True, verbose_name="Executed At")

    class Meta(BaseModel.Meta):
        verbose_name = "Rule Execution"
        verbose_name_plural = "Rule Executions"
        ordering = ["-executed_at"]

    def __str__(self):
        return f"Execution of {self.rule.rule_code} on {self.resume.resume_title}: {self.status}"


class ProfessionProfile(BaseModel):
    """
    Profile defining required/recommended settings, skills, expectations and weights
    for a specific profession/role.
    """
    role = models.CharField(
        max_length=100,
        unique=True,
        verbose_name="Role / Profession"
    )
    industry = models.CharField(
        max_length=100,
        verbose_name="Industry"
    )
    required_sections = models.JSONField(
        default=list,
        verbose_name="Required Sections"
    )
    optional_sections = models.JSONField(
        default=list,
        verbose_name="Optional Sections"
    )
    required_skills = models.JSONField(
        default=list,
        verbose_name="Required Skills"
    )
    recommended_skills = models.JSONField(
        default=list,
        verbose_name="Recommended Skills"
    )
    soft_skills = models.JSONField(
        default=list,
        verbose_name="Soft Skills"
    )
    preferred_certifications = models.JSONField(
        default=list,
        verbose_name="Preferred Certifications"
    )
    expected_projects = models.JSONField(
        default=list,
        verbose_name="Expected Projects"
    )
    weights = models.JSONField(
        default=dict,
        verbose_name="Weight Distribution"
    )
    penalties = models.JSONField(
        default=list,
        verbose_name="Penalty Rules"
    )
    bonuses = models.JSONField(
        default=list,
        verbose_name="Bonus Rules"
    )
    benchmark_group = models.CharField(
        max_length=100,
        default="General",
        verbose_name="Benchmark Group"
    )
    enabled = models.BooleanField(
        default=True,
        verbose_name="Enabled"
    )

    class Meta(BaseModel.Meta):
        verbose_name = "Profession Profile"
        verbose_name_plural = "Profession Profiles"
        ordering = ["role"]

    def __str__(self):
        return self.role


class CategoryScore(BaseModel):
    """
    Quality score details calculated independently for a specific resume category.
    """
    resume = models.ForeignKey(
        Resume,
        on_delete=models.CASCADE,
        related_name="category_scores",
        verbose_name="Resume"
    )
    category = models.CharField(
        max_length=100,
        verbose_name="Category Name"
    )
    score = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Category Score"
    )
    confidence = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Confidence Score"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Created At"
    )

    class Meta(BaseModel.Meta):
        verbose_name = "Category Score"
        verbose_name_plural = "Category Scores"
        unique_together = ("resume", "category")
        ordering = ["category"]

    def __str__(self):
        return f"{self.category}: {self.score}/100 – {self.resume.resume_title}"
class ExplanationReport(BaseModel):
    """
    Detailed explainability report for a resume's ATS score.
    """
    resume = models.ForeignKey(
        Resume,
        on_delete=models.CASCADE,
        related_name="explanation_reports",
        verbose_name="Resume"
    )
    overall_score = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Overall ATS Score"
    )
    confidence = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        default=95,
        verbose_name="Explanation Confidence"
    )
    natural_language_report = models.TextField(
        verbose_name="Natural Language Explanation"
    )
    category_explanations = models.JSONField(
        default=dict,
        verbose_name="Category Explanations Breakdown"
    )
    ats_score_breakdown = models.JSONField(
        default=dict,
        verbose_name="ATS Score Breakdown"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Created At"
    )

    class Meta(BaseModel.Meta):
        verbose_name = "Explanation Report"
        verbose_name_plural = "Explanation Reports"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Explanation: {self.overall_score}/100 – {self.resume.resume_title}"


class RecommendationHistory(BaseModel):
    """
    Stores individual recommendations for a resume's score improvement.
    Tracks whether the candidate implemented them.
    """
    resume = models.ForeignKey(
        Resume,
        on_delete=models.CASCADE,
        related_name="recommendation_histories",
        verbose_name="Resume"
    )
    category = models.CharField(
        max_length=100,
        verbose_name="Category"
    )
    recommendation_text = models.TextField(
        verbose_name="Recommendation Text"
    )
    priority = models.CharField(
        max_length=20,
        choices=[
            ("critical", "Critical"),
            ("high", "High"),
            ("medium", "Medium"),
            ("low", "Low")
        ],
        verbose_name="Priority"
    )
    score_impact = models.IntegerField(
        verbose_name="Score Impact"
    )
    implemented = models.BooleanField(
        default=False,
        verbose_name="Implemented"
    )
    applied_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name="Applied At"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Created At"
    )

    class Meta(BaseModel.Meta):
        verbose_name = "Recommendation History"
        verbose_name_plural = "Recommendation Histories"
        ordering = ["-created_at"]

    def __str__(self):
        status = "Done" if self.implemented else "Pending"
        return f"[{status}] {self.category} ({self.priority}) – {self.resume.resume_title}"


class ImprovementSimulation(BaseModel):
    """
    Stores score simulations calculated by the user.
    """
    resume = models.ForeignKey(
        Resume,
        on_delete=models.CASCADE,
        related_name="improvement_simulations",
        verbose_name="Resume"
    )
    current_score = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Current Score"
    )
    simulated_actions = models.JSONField(
        default=list,
        verbose_name="Simulated Actions"
    )
    estimated_score = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Estimated Score"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Created At"
    )

    class Meta(BaseModel.Meta):
        verbose_name = "Improvement Simulation"
        verbose_name_plural = "Improvement Simulations"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Sim: {self.current_score} -> {self.estimated_score} – {self.resume.resume_title}"


# ---------------------------------------------------------------------------
# Phase H: Calibration, Validation & Continuous Learning Engine Models
# ---------------------------------------------------------------------------

class CalibrationReport(BaseModel):
    """
    Persists calibration audits containing engine health scores and system warnings.
    """
    engine_health = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Engine Health"
    )
    score_distribution = models.CharField(
        max_length=50,
        verbose_name="Score Distribution State"
    )
    rule_coverage = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Rule Coverage"
    )
    duplicate_rules = models.IntegerField(verbose_name="Duplicate Rules Count")
    unused_rules = models.IntegerField(verbose_name="Unused Rules Count")
    profession_accuracy = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name="Profession Accuracy"
    )
    recommendations = models.JSONField(
        default=list,
        verbose_name="Optimization Recommendations"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Created At"
    )

    class Meta(BaseModel.Meta):
        verbose_name = "Calibration Report"
        verbose_name_plural = "Calibration Reports"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Calib Health: {self.engine_health}% ({self.created_at.date()})"


class ValidationRun(BaseModel):
    """
    Logs details of automated validation sweeps.
    """
    run_type = models.CharField(
        max_length=50,
        default="automated",
        verbose_name="Run Type"
    )
    total_tests = models.IntegerField(verbose_name="Total Tests Run")
    successful_tests = models.IntegerField(verbose_name="Successful Tests")
    failed_tests = models.IntegerField(verbose_name="Failed Tests")
    accuracy_rate = models.FloatField(verbose_name="Accuracy Rate")
    error_log = models.JSONField(
        default=list,
        verbose_name="Anomalies and Errors Log"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Created At"
    )

    class Meta(BaseModel.Meta):
        verbose_name = "Validation Run"
        verbose_name_plural = "Validation Runs"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Validation {self.id[:8]} - Acc: {self.accuracy_rate:.1f}%"


class RuleMetrics(BaseModel):
    """
    Stores metrics on rule execution frequency, pass rates, and conflict detections.
    """
    rule_code = models.CharField(max_length=100, unique=True, verbose_name="Rule Code")
    rule_name = models.CharField(max_length=200, verbose_name="Rule Name")
    times_executed = models.IntegerField(default=0, verbose_name="Times Executed")
    times_passed = models.IntegerField(default=0, verbose_name="Times Passed")
    times_failed = models.IntegerField(default=0, verbose_name="Times Failed")
    pass_rate = models.FloatField(default=0.0, verbose_name="Pass Rate")
    is_unused = models.BooleanField(default=False, verbose_name="Is Unused")
    is_redundant = models.BooleanField(default=False, verbose_name="Is Redundant")
    conflicts_with = models.JSONField(default=list, verbose_name="Conflicting Rules")

    class Meta(BaseModel.Meta):
        verbose_name = "Rule Metric"
        verbose_name_plural = "Rule Metrics"

    def __str__(self):
        return f"{self.rule_code} (Pass: {self.pass_rate:.1f}%)"


class DistributionMetrics(BaseModel):
    """
    Stores score statistical distribution metrics.
    """
    dataset_name = models.CharField(max_length=100, verbose_name="Dataset Name")
    total_scores = models.IntegerField(verbose_name="Total Scores Analyzed")
    average_score = models.FloatField(verbose_name="Average Score")
    median_score = models.FloatField(verbose_name="Median Score")
    variance = models.FloatField(verbose_name="Variance")
    std_dev = models.FloatField(verbose_name="Standard Deviation")
    score_ranges = models.JSONField(
        default=dict,
        verbose_name="Score Range Frequencies"
    )
    skewness = models.FloatField(default=0.0, verbose_name="Skewness")
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Created At"
    )

    class Meta(BaseModel.Meta):
        verbose_name = "Distribution Metric"
        verbose_name_plural = "Distribution Metrics"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Dist: {self.dataset_name} (Avg: {self.average_score:.1f})"

