class WeightEngine:
    """
    Decides the weights for all 25 subscores dynamically depending on the predicted profession.
    The sum of all weights must equal 100% (1.0).
    """

    DEFAULT_WEIGHTS = {
        "structure": 0.04,
        "compatibility": 0.04,
        "contact": 0.04,
        "summary": 0.04,
        "skills": 0.08,
        "skill_relevance": 0.06,
        "experience": 0.10,
        "experience_quality": 0.10,
        "projects": 0.06,
        "project_quality": 0.06,
        "education": 0.05,
        "certifications": 0.03,
        "achievements": 0.04,
        "leadership": 0.03,
        "keywords": 0.06,
        "formatting": 0.03,
        "readability": 0.03,
        "grammar": 0.03,
        "action_verbs": 0.03,
        "quantified_achievements": 0.03,
        "portfolio": 0.01,
        "linkedin": 0.01,
        "github": 0.01,
        "progression": 0.02,
        "consistency": 0.02,
    }

    # Custom weights mapped by profession
    PROFESSION_WEIGHTS = {
        "Software Engineer": {
            "skills": 0.12,
            "skill_relevance": 0.08,
            "projects": 0.10,
            "project_quality": 0.10,
            "github": 0.05,
            "experience": 0.10,
            "experience_quality": 0.10,
            "education": 0.05,
            "quantified_achievements": 0.05,
            "action_verbs": 0.04,
            "portfolio": 0.03,
            "linkedin": 0.02,
            # Adjust the rest so total sums to 1.0
            "structure": 0.02,
            "compatibility": 0.02,
            "contact": 0.02,
            "summary": 0.02,
            "certifications": 0.02,
            "achievements": 0.02,
            "leadership": 0.02,
            "keywords": 0.04,
            "formatting": 0.01,
            "readability": 0.01,
            "grammar": 0.01,
            "progression": 0.02,
            "consistency": 0.02,
        },
        "AI Engineer": {
            "skills": 0.14,
            "skill_relevance": 0.10,
            "projects": 0.10,
            "project_quality": 0.10,
            "github": 0.06,
            "experience": 0.08,
            "experience_quality": 0.08,
            "education": 0.08,  # AI/ML roles often value higher education degrees
            "quantified_achievements": 0.04,
            "portfolio": 0.02,
            "linkedin": 0.02,
            "structure": 0.02,
            "compatibility": 0.02,
            "contact": 0.02,
            "summary": 0.02,
            "certifications": 0.02,
            "achievements": 0.02,
            "leadership": 0.02,
            "keywords": 0.03,
            "formatting": 0.01,
            "readability": 0.01,
            "grammar": 0.01,
            "action_verbs": 0.02,
            "progression": 0.01,
            "consistency": 0.02,
        },
        "Data Analyst": {
            "skills": 0.12,
            "skill_relevance": 0.08,
            "projects": 0.10,
            "project_quality": 0.08,
            "experience": 0.12,
            "experience_quality": 0.12,
            "education": 0.06,
            "keywords": 0.08,
            "quantified_achievements": 0.06,
            "github": 0.03,
            "linkedin": 0.02,
            "structure": 0.02,
            "compatibility": 0.02,
            "contact": 0.02,
            "summary": 0.02,
            "certifications": 0.02,
            "achievements": 0.01,
            "leadership": 0.01,
            "formatting": 0.01,
            "readability": 0.01,
            "grammar": 0.01,
            "action_verbs": 0.01,
            "portfolio": 0.01,
            "progression": 0.01,
            "consistency": 0.02,
        },
        "UI Designer": {
            "portfolio": 0.12,
            "projects": 0.12,
            "project_quality": 0.12,
            "skills": 0.10,
            "skill_relevance": 0.08,
            "formatting": 0.08,  # UI designers should have perfect layouts
            "experience": 0.08,
            "experience_quality": 0.08,
            "linkedin": 0.03,
            "education": 0.03,
            "structure": 0.02,
            "compatibility": 0.02,
            "contact": 0.02,
            "summary": 0.02,
            "certifications": 0.02,
            "achievements": 0.01,
            "leadership": 0.01,
            "keywords": 0.03,
            "readability": 0.01,
            "grammar": 0.01,
            "action_verbs": 0.01,
            "github": 0.00,
            "quantified_achievements": 0.02,
            "progression": 0.01,
            "consistency": 0.02,
        },
        "Teacher": {
            "experience": 0.20,
            "experience_quality": 0.15,
            "education": 0.15,
            "leadership": 0.10,
            "readability": 0.06,
            "grammar": 0.06,
            "skills": 0.06,
            "skill_relevance": 0.06,
            "summary": 0.05,
            "certifications": 0.05,
            "contact": 0.02,
            "structure": 0.02,
            "compatibility": 0.01,
            "projects": 0.00,
            "project_quality": 0.00,
            "achievements": 0.01,
            "keywords": 0.01,
            "formatting": 0.01,
            "action_verbs": 0.01,
            "quantified_achievements": 0.01,
            "portfolio": 0.00,
            "linkedin": 0.01,
            "github": 0.00,
            "progression": 0.01,
            "consistency": 0.01,
        },
        "Doctor": {
            "experience": 0.25,
            "experience_quality": 0.20,
            "education": 0.20,
            "certifications": 0.10,
            "skills": 0.08,
            "skill_relevance": 0.05,
            "contact": 0.04,
            "structure": 0.02,
            "summary": 0.02,
            "compatibility": 0.01,
            "projects": 0.00,
            "project_quality": 0.00,
            "achievements": 0.01,
            "leadership": 0.01,
            "keywords": 0.01,
            "formatting": 0.00,
            "readability": 0.00,
            "grammar": 0.00,
            "action_verbs": 0.00,
            "quantified_achievements": 0.00,
            "portfolio": 0.00,
            "linkedin": 0.00,
            "github": 0.00,
            "progression": 0.00,
            "consistency": 0.00,
        },
        "Lawyer": {
            "experience": 0.20,
            "experience_quality": 0.20,
            "education": 0.15,
            "readability": 0.08,
            "grammar": 0.08,
            "skills": 0.06,
            "skill_relevance": 0.06,
            "summary": 0.04,
            "certifications": 0.04,
            "leadership": 0.04,
            "contact": 0.02,
            "structure": 0.02,
            "compatibility": 0.01,
            "projects": 0.00,
            "project_quality": 0.00,
            "achievements": 0.01,
            "keywords": 0.01,
            "formatting": 0.01,
            "action_verbs": 0.01,
            "quantified_achievements": 0.01,
            "portfolio": 0.00,
            "linkedin": 0.01,
            "github": 0.00,
            "progression": 0.01,
            "consistency": 0.01,
        },
        "Student": {
            "education": 0.18,
            "projects": 0.15,
            "project_quality": 0.15,
            "skills": 0.12,
            "skill_relevance": 0.08,
            "structure": 0.06,
            "grammar": 0.05,
            "readability": 0.05,
            "github": 0.04,
            "portfolio": 0.04,
            "experience": 0.03,
            "experience_quality": 0.03,
            "contact": 0.02,
            "summary": 0.02,
            "compatibility": 0.01,
            "certifications": 0.01,
            "achievements": 0.01,
            "leadership": 0.01,
            "keywords": 0.01,
            "formatting": 0.01,
            "action_verbs": 0.01,
            "quantified_achievements": 0.01,
            "linkedin": 0.01,
            "progression": 0.00,
            "consistency": 0.00,
        },
        "Freelancer": {
            "projects": 0.18,
            "project_quality": 0.15,
            "skills": 0.12,
            "skill_relevance": 0.10,
            "portfolio": 0.10,
            "experience": 0.08,
            "experience_quality": 0.08,
            "linkedin": 0.05,
            "summary": 0.04,
            "contact": 0.04,
            "structure": 0.02,
            "compatibility": 0.01,
            "education": 0.01,
            "certifications": 0.01,
            "achievements": 0.01,
            "leadership": 0.00,
            "keywords": 0.02,
            "formatting": 0.01,
            "readability": 0.01,
            "grammar": 0.01,
            "action_verbs": 0.01,
            "quantified_achievements": 0.01,
            "github": 0.02,
            "progression": 0.01,
            "consistency": 0.01,
        }
    }

    @classmethod
    def get_weights(cls, profession: str) -> dict:
        """
        Returns a normalized dict of weights that sums to exactly 1.0.
        """
        weights = cls.PROFESSION_WEIGHTS.get(profession, cls.DEFAULT_WEIGHTS).copy()
        
        # Ensure all 25 subscores exist in the returned dictionary
        for key in cls.DEFAULT_WEIGHTS:
            if key not in weights:
                weights[key] = 0.0
        
        # Normalize to sum to exactly 1.0 to prevent minor float rounding drift
        total = sum(weights.values())
        if total > 0:
            keys = list(weights.keys())
            running_sum = 0.0
            for key in keys[:-1]:
                val = round(weights[key] / total, 4)
                weights[key] = val
                running_sum += val
            # Assign the remainder to the last key
            weights[keys[-1]] = round(1.0 - running_sum, 4)
        
        return weights
