# Generated by Django 5.2.15 on 2026-06-26 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Edited At'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AddField(
            model_name='profile',
            name='source_of_value',
            field=models.JSONField(blank=True, default=dict, help_text="Maps field names to their source (e.g. 'regex', 'spacy', 'gemini', 'manual').", verbose_name='Source of Value Map'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('soft', 'Soft')], default='general', max_length=20, verbose_name='Skill Type'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('profile', 'skill_name', 'skill_type')},
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('description', models.TextField(verbose_name='Achievement Description')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='profiles.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=200, verbose_name='Award Title')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='Award Issuer')),
                ('date_awarded', models.DateField(blank=True, null=True, verbose_name='Date Awarded')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='profiles.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'ordering': ['-date_awarded'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileEditHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('section', models.CharField(help_text='e.g. personal, skills, experience, education, projects', max_length=50, verbose_name='Profile Section')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='manual', help_text='e.g. regex, spacy, gemini, manual', max_length=50, verbose_name='Source of Value')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_edits', to=settings.AUTH_USER_MODEL, verbose_name='Edited By')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='profiles.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Profile Edit History',
                'verbose_name_plural': 'Profile Edit Histories',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Publication Title')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='Publisher / Journal')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Publication Date')),
                ('url', models.URLField(blank=True, verbose_name='Publication URL')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='profiles.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-publication_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, verbose_name='Reference Name')),
                ('relationship', models.CharField(blank=True, max_length=200, verbose_name='Relationship')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Company / Organization')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Contact Info')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='profiles.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('organization', models.CharField(max_length=200, verbose_name='Organization')),
                ('role', models.CharField(max_length=200, verbose_name='Role / Designation')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_work', to='profiles.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Volunteer Work',
                'verbose_name_plural': 'Volunteer Work Records',
                'ordering': ['-end_date', '-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('hobby_name', models.CharField(max_length=100, verbose_name='Hobby Name')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='profiles.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Hobby',
                'verbose_name_plural': 'Hobbies',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('profile', 'hobby_name')},
            },
        ),
    ]
