# Generated by Django 5.2.15 on 2026-06-27 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_alter_skill_unique_together_profile_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('career_readiness', models.IntegerField(default=70, verbose_name='Career Readiness Score')),
                ('growth_score', models.IntegerField(default=70, verbose_name='Growth Score')),
                ('learning_score', models.IntegerField(default=70, verbose_name='Learning Score')),
                ('industry_alignment', models.IntegerField(default=70, verbose_name='Industry Alignment')),
                ('skill_strength', models.IntegerField(default=70, verbose_name='Skill Strength')),
                ('market_demand', models.IntegerField(default=70, verbose_name='Market Demand')),
                ('career_json', models.JSONField(blank=True, default=dict, help_text='Stores current role, stage, strengths, weaknesses, directions, role suggestions.', verbose_name='Career Analysis JSON')),
                ('roadmap_json', models.JSONField(blank=True, default=dict, help_text='Stores sequenced technologies, courses, books, certifications, duration details.', verbose_name='Learning Roadmap JSON')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_profile', to='profiles.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Career Profile',
                'verbose_name_plural': 'Career Profiles',
            },
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.CharField(max_length=200, verbose_name='Company Name')),
                ('position', models.CharField(max_length=200, verbose_name='Position/Job Role')),
                ('job_description', models.TextField(blank=True, verbose_name='Job Description')),
                ('tone', models.CharField(max_length=50, verbose_name='Cover Letter Tone')),
                ('cover_letter_type', models.CharField(max_length=100, verbose_name='Letter Type')),
                ('content', models.TextField(verbose_name='Cover Letter Body')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cover Letter',
                'verbose_name_plural': 'Cover Letters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgressLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('milestone_title', models.CharField(max_length=200, verbose_name='Roadmap Milestone')),
                ('item_name', models.CharField(max_length=200, verbose_name='Target Technology/Course')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Learning Progress Log',
                'verbose_name_plural': 'Learning Progress Logs',
                'unique_together': {('user', 'milestone_title', 'item_name')},
            },
        ),
    ]
