# Generated by Django 5.2.15 on 2026-06-26 07:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('theme', models.CharField(choices=[('minimal', 'Minimal'), ('modern', 'Modern'), ('classic', 'Classic'), ('dark', 'Dark'), ('creative', 'Creative')], default='modern', max_length=20, verbose_name='Theme')),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='Is Public')),
                ('slug', models.SlugField(help_text='Unique slug for the public portfolio URL.', max_length=100, unique=True, verbose_name='URL Slug')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='profiles.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['slug'], name='idx_portfolio_slug')],
            },
        ),
    ]
