# Generated by Django 5.2.15 on 2026-06-27 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='downloads',
            field=models.IntegerField(default=0, verbose_name='Downloads Count'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_generated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Generated At'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes Count'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_json',
            field=models.JSONField(blank=True, help_text='Snapshot of verified master resume profile JSON.', null=True, verbose_name='Portfolio JSON Data'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='shares',
            field=models.IntegerField(default=0, verbose_name='Shares Count'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views Count'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='theme',
            field=models.CharField(choices=[('modern', 'Modern'), ('minimal', 'Minimal'), ('developer', 'Developer'), ('corporate', 'Corporate'), ('creative', 'Creative'), ('dark', 'Dark'), ('light', 'Light'), ('glassmorphism', 'Glassmorphism'), ('professional', 'Professional'), ('student', 'Student'), ('researcher', 'Researcher')], default='modern', max_length=20, verbose_name='Theme'),
        ),
        migrations.CreateModel(
            name='PortfolioAnalyticsLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('event_type', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('share', 'Share'), ('section_view', 'Section View')], default='view', max_length=20, verbose_name='Event Type')),
                ('section_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Section Name')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='portfolio.portfolio', verbose_name='Portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Analytics Log',
                'verbose_name_plural': 'Portfolio Analytics Logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
