# Generated by Django 5.2.15 on 2026-06-26 07:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('score', models.DecimalField(decimal_places=2, help_text='Overall ATS compatibility score (0-100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Overall ATS Score')),
                ('keyword_score', models.DecimalField(decimal_places=2, help_text='Keyword match score (0-100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Keyword Score')),
                ('formatting_score', models.DecimalField(decimal_places=2, help_text='Formatting quality score (0-100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Formatting Score')),
                ('grammar_score', models.DecimalField(decimal_places=2, help_text='Grammar and language score (0-100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Grammar Score')),
                ('suggestions', models.JSONField(blank=True, help_text='AI-generated improvement suggestions (structured list).', null=True, verbose_name='Suggestions')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_score', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'ATS Score',
                'verbose_name_plural': 'ATS Scores',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
