# Generated by Django 5.2.15 on 2026-06-27 09:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
        ('resumes', '0007_resume_completion_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atsscore',
            options={'ordering': ['-ats_completed_at'], 'verbose_name': 'ATS Score', 'verbose_name_plural': 'ATS Scores'},
        ),
        migrations.RenameField(
            model_name='atsscore',
            old_name='score',
            new_name='ats_score',
        ),
        migrations.RemoveField(
            model_name='atsscore',
            name='formatting_score',
        ),
        migrations.RemoveField(
            model_name='atsscore',
            name='grammar_score',
        ),
        migrations.RemoveField(
            model_name='atsscore',
            name='keyword_score',
        ),
        migrations.AddField(
            model_name='atsscore',
            name='ats_completed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Completed At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atsscore',
            name='ats_json',
            field=models.JSONField(default={}, help_text='Detailed JSON containing all sub-scores, keyword analyses, grammar notes, and stats.', verbose_name='ATS Analysis JSON'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atsscore',
            name='ats_processing_time',
            field=models.FloatField(default=0.0, help_text='Time taken to perform the ATS analysis in seconds.', verbose_name='Processing Time (Seconds)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atsscore',
            name='industry_match',
            field=models.JSONField(default={}, help_text='List/dict of industry match percentages.', verbose_name='Industry Matches'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atsscore',
            name='missing_skills',
            field=models.JSONField(default=[], help_text='Suggested skills based on detected primary industry.', verbose_name='Missing Skills'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atsscore',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_analyses', to='resumes.resume', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='atsscore',
            name='suggestions',
            field=models.JSONField(default=[], help_text='Actionable suggestions categorized by priority.', verbose_name='Suggestions'),
            preserve_default=False,
        ),
    ]
