# Generated by Django 5.2.15 on 2026-07-16 05:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_alter_atsscore_options_and_more'),
        ('resumes', '0016_copilotaction_copilotconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSBenchmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('profession', models.CharField(max_length=100, unique=True, verbose_name='Profession/Role Name')),
                ('percentile_25', models.IntegerField(default=55)),
                ('percentile_50', models.IntegerField(default=70)),
                ('percentile_75', models.IntegerField(default=82)),
                ('percentile_90', models.IntegerField(default=92)),
                ('average_score', models.IntegerField(default=68)),
            ],
            options={
                'verbose_name': 'ATS Benchmark',
                'verbose_name_plural': 'ATS Benchmarks',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ATSRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('suggestion', models.TextField(verbose_name='Actionable Suggestion')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('optional', 'Optional')], default='important', max_length=20)),
                ('potential_boost', models.IntegerField(default=5, verbose_name='Potential Score Boost')),
            ],
            options={
                'verbose_name': 'ATS Recommendation',
                'verbose_name_plural': 'ATS Recommendations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ATSReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('overall_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Overall ATS Score')),
                ('confidence', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Confidence Score')),
                ('job_ready', models.BooleanField(default=False, verbose_name='Job Ready Status')),
                ('parsing_quality', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Parsing Quality')),
                ('strengths', models.JSONField(default=list, verbose_name='Strengths List')),
                ('weaknesses', models.JSONField(default=list, verbose_name='Weaknesses List')),
                ('recommendations', models.JSONField(default=list, verbose_name='Recommendations')),
                ('subscores', models.JSONField(default=dict, verbose_name='Sub-scores Breakdown')),
                ('job_description_text', models.TextField(blank=True, null=True, verbose_name='Target Job Description')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_reports', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'ATS Report',
                'verbose_name_plural': 'ATS Reports',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ATSHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('overall_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Overall Score')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Completed At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_history_logs', to='resumes.resume', verbose_name='Resume')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_links', to='ats.atsreport', verbose_name='Linked Report')),
            ],
            options={
                'verbose_name': 'ATS History Log',
                'verbose_name_plural': 'ATS History Logs',
                'ordering': ['-completed_at'],
                'abstract': False,
            },
        ),
    ]
