# Generated by Django 5.2.15 on 2026-07-16 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0003_atsbenchmark_atsrecommendation_atsreport_atshistory'),
        ('resumes', '0016_copilotaction_copilotconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('weight', models.FloatField(default=1.0, verbose_name='Category Weight')),
            ],
            options={
                'verbose_name': 'Rule Category',
                'verbose_name_plural': 'Rule Categories',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ATSRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('rule_code', models.CharField(max_length=100, unique=True, verbose_name='Rule Code')),
                ('name', models.CharField(max_length=255, verbose_name='Rule Name')),
                ('description', models.TextField(verbose_name='Rule Description')),
                ('condition', models.TextField(verbose_name='Condition (Python Expression)')),
                ('points', models.IntegerField(default=0, verbose_name='Points / Score Impact')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('profession', models.CharField(default='All', max_length=100, verbose_name='Target Profession')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('recommendation', models.TextField(verbose_name='Recommendation on Failure')),
                ('explanation', models.TextField(verbose_name='Explanation / Logic')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ats.rulecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'ATS Rule',
                'verbose_name_plural': 'ATS Rules',
                'ordering': ['rule_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='skipped', max_length=20)),
                ('score_impact', models.IntegerField(default=0, verbose_name='Score Impact')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Execution Reason / Explanation')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='Actionable Recommendation')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Executed At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_executions', to='resumes.resume', verbose_name='Resume')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ats.atsrule', verbose_name='Rule')),
            ],
            options={
                'verbose_name': 'Rule Execution',
                'verbose_name_plural': 'Rule Executions',
                'ordering': ['-executed_at'],
                'abstract': False,
            },
        ),
    ]
