# Generated by Django 5.2.15 on 2026-07-16 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0004_rulecategory_atsrule_ruleexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('role', models.CharField(max_length=100, unique=True, verbose_name='Role / Profession')),
                ('industry', models.CharField(max_length=100, verbose_name='Industry')),
                ('required_sections', models.JSONField(default=list, verbose_name='Required Sections')),
                ('optional_sections', models.JSONField(default=list, verbose_name='Optional Sections')),
                ('required_skills', models.JSONField(default=list, verbose_name='Required Skills')),
                ('recommended_skills', models.JSONField(default=list, verbose_name='Recommended Skills')),
                ('soft_skills', models.JSONField(default=list, verbose_name='Soft Skills')),
                ('preferred_certifications', models.JSONField(default=list, verbose_name='Preferred Certifications')),
                ('expected_projects', models.JSONField(default=list, verbose_name='Expected Projects')),
                ('weights', models.JSONField(default=dict, verbose_name='Weight Distribution')),
                ('penalties', models.JSONField(default=list, verbose_name='Penalty Rules')),
                ('bonuses', models.JSONField(default=list, verbose_name='Bonus Rules')),
                ('benchmark_group', models.CharField(default='General', max_length=100, verbose_name='Benchmark Group')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Profession Profile',
                'verbose_name_plural': 'Profession Profiles',
                'ordering': ['role'],
                'abstract': False,
            },
        ),
    ]
