# Generated by Django 5.2.15 on 2026-07-17 04:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0005_professionprofile'),
        ('resumes', '0016_copilotaction_copilotconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.CharField(max_length=100, verbose_name='Category Name')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Category Score')),
                ('confidence', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Confidence Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Category Score',
                'verbose_name_plural': 'Category Scores',
                'ordering': ['category'],
                'abstract': False,
                'unique_together': {('resume', 'category')},
            },
        ),
    ]
