# Generated by Django 5.2.15 on 2026-07-19 05:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0006_categoryscore'),
        ('resumes', '0016_copilotaction_copilotconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplanationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('overall_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Overall ATS Score')),
                ('confidence', models.IntegerField(default=95, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Explanation Confidence')),
                ('natural_language_report', models.TextField(verbose_name='Natural Language Explanation')),
                ('category_explanations', models.JSONField(default=dict, verbose_name='Category Explanations Breakdown')),
                ('ats_score_breakdown', models.JSONField(default=dict, verbose_name='ATS Score Breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanation_reports', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Explanation Report',
                'verbose_name_plural': 'Explanation Reports',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImprovementSimulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('current_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Current Score')),
                ('simulated_actions', models.JSONField(default=list, verbose_name='Simulated Actions')),
                ('estimated_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Estimated Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_simulations', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Improvement Simulation',
                'verbose_name_plural': 'Improvement Simulations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('recommendation_text', models.TextField(verbose_name='Recommendation Text')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, verbose_name='Priority')),
                ('score_impact', models.IntegerField(verbose_name='Score Impact')),
                ('implemented', models.BooleanField(default=False, verbose_name='Implemented')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Applied At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_histories', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Recommendation History',
                'verbose_name_plural': 'Recommendation Histories',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
