# Generated by Django 5.2.15 on 2026-07-19 05:53

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0007_explanationreport_improvementsimulation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('engine_health', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Engine Health')),
                ('score_distribution', models.CharField(max_length=50, verbose_name='Score Distribution State')),
                ('rule_coverage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rule Coverage')),
                ('duplicate_rules', models.IntegerField(verbose_name='Duplicate Rules Count')),
                ('unused_rules', models.IntegerField(verbose_name='Unused Rules Count')),
                ('profession_accuracy', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Profession Accuracy')),
                ('recommendations', models.JSONField(default=list, verbose_name='Optimization Recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Calibration Report',
                'verbose_name_plural': 'Calibration Reports',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistributionMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('dataset_name', models.CharField(max_length=100, verbose_name='Dataset Name')),
                ('total_scores', models.IntegerField(verbose_name='Total Scores Analyzed')),
                ('average_score', models.FloatField(verbose_name='Average Score')),
                ('median_score', models.FloatField(verbose_name='Median Score')),
                ('variance', models.FloatField(verbose_name='Variance')),
                ('std_dev', models.FloatField(verbose_name='Standard Deviation')),
                ('score_ranges', models.JSONField(default=dict, verbose_name='Score Range Frequencies')),
                ('skewness', models.FloatField(default=0.0, verbose_name='Skewness')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Distribution Metric',
                'verbose_name_plural': 'Distribution Metrics',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('rule_code', models.CharField(max_length=100, unique=True, verbose_name='Rule Code')),
                ('rule_name', models.CharField(max_length=200, verbose_name='Rule Name')),
                ('times_executed', models.IntegerField(default=0, verbose_name='Times Executed')),
                ('times_passed', models.IntegerField(default=0, verbose_name='Times Passed')),
                ('times_failed', models.IntegerField(default=0, verbose_name='Times Failed')),
                ('pass_rate', models.FloatField(default=0.0, verbose_name='Pass Rate')),
                ('is_unused', models.BooleanField(default=False, verbose_name='Is Unused')),
                ('is_redundant', models.BooleanField(default=False, verbose_name='Is Redundant')),
                ('conflicts_with', models.JSONField(default=list, verbose_name='Conflicting Rules')),
            ],
            options={
                'verbose_name': 'Rule Metric',
                'verbose_name_plural': 'Rule Metrics',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('run_type', models.CharField(default='automated', max_length=50, verbose_name='Run Type')),
                ('total_tests', models.IntegerField(verbose_name='Total Tests Run')),
                ('successful_tests', models.IntegerField(verbose_name='Successful Tests')),
                ('failed_tests', models.IntegerField(verbose_name='Failed Tests')),
                ('accuracy_rate', models.FloatField(verbose_name='Accuracy Rate')),
                ('error_log', models.JSONField(default=list, verbose_name='Anomalies and Errors Log')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Validation Run',
                'verbose_name_plural': 'Validation Runs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
