# Generated by Django 5.2.15 on 2026-07-07 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0016_copilotaction_copilotconversation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Job Title')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('industry', models.CharField(blank=True, max_length=255, verbose_name='Industry')),
                ('content', models.TextField(verbose_name='Raw JD Content')),
                ('parsed_data', models.JSONField(blank=True, default=dict, help_text='Structured extraction: sections, skills, requirements, etc.', verbose_name='Parsed Data')),
                ('source_type', models.CharField(choices=[('text', 'Plain Text'), ('pdf', 'PDF Document'), ('docx', 'Word Document'), ('url', 'URL')], default='text', max_length=10, verbose_name='Source Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('match_score', models.IntegerField(default=0, verbose_name='Overall Match Score')),
                ('ats_score', models.IntegerField(default=0, verbose_name='ATS Score')),
                ('skills_match', models.IntegerField(default=0, verbose_name='Skills Match %')),
                ('experience_match', models.IntegerField(default=0, verbose_name='Experience Match %')),
                ('education_match', models.IntegerField(default=0, verbose_name='Education Match %')),
                ('keyword_match', models.IntegerField(default=0, verbose_name='Keyword Match %')),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('matching_skills', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('interview_readiness', models.JSONField(blank=True, default=dict)),
                ('salary_estimate', models.JSONField(blank=True, default=dict)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jd_analyses', to='resumes.resume', verbose_name='Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jd_analyses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='jd_analyzer.jobdescription', verbose_name='Job Description')),
            ],
            options={
                'verbose_name': 'Job Analysis',
                'verbose_name_plural': 'Job Analyses',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
