# Generated by Django 5.2.15 on 2026-07-07 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0016_copilotaction_copilotconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('score', models.IntegerField(default=0, verbose_name='Match Score')),
                ('salary', models.CharField(blank=True, max_length=100, verbose_name='Salary Range')),
                ('industry', models.CharField(blank=True, max_length=255, verbose_name='Industry')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('remote', models.BooleanField(default=False, verbose_name='Remote Eligible')),
                ('missing_skills', models.JSONField(blank=True, default=list, verbose_name='Missing Skills')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Job Recommendation',
                'verbose_name_plural': 'Job Recommendations',
                'ordering': ['-score', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('skill', models.CharField(max_length=150, verbose_name='Skill Name')),
                ('importance', models.CharField(default='Medium', max_length=50, verbose_name='Importance Level')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Skill Gap',
                'verbose_name_plural': 'Skill Gaps',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('resume', 'skill')},
            },
        ),
    ]
