# Generated by Django 5.2.15 on 2026-07-18 03:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0016_copilotaction_copilotconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewReadiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('technical_score', models.IntegerField(default=0, verbose_name='Technical Skills Score')),
                ('projects_score', models.IntegerField(default=0, verbose_name='Projects Score')),
                ('experience_score', models.IntegerField(default=0, verbose_name='Experience Score')),
                ('leadership_score', models.IntegerField(default=0, verbose_name='Leadership Score')),
                ('communication_score', models.IntegerField(default=0, verbose_name='Communication Score')),
                ('overall_readiness', models.CharField(max_length=100, verbose_name='Overall Readiness Status')),
                ('feedback', models.JSONField(blank=True, default=list, verbose_name='Detailed Feedback')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_readiness_records', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Interview Readiness',
                'verbose_name_plural': 'Interview Readiness Records',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobATSReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('job_description', models.TextField(verbose_name='Job Description')),
                ('overall_match', models.IntegerField(default=0, verbose_name='Overall Match %')),
                ('ats_score', models.IntegerField(default=0, verbose_name='ATS Score %')),
                ('interview_readiness', models.CharField(default='Needs Improvement', max_length=100, verbose_name='Interview Readiness')),
                ('role_match', models.IntegerField(default=0, verbose_name='Role Match %')),
                ('skills_match', models.IntegerField(default=0, verbose_name='Skills Match %')),
                ('experience_match', models.IntegerField(default=0, verbose_name='Experience Match %')),
                ('education_match', models.IntegerField(default=0, verbose_name='Education Match %')),
                ('projects_match', models.IntegerField(default=0, verbose_name='Projects Match %')),
                ('missing_skills', models.JSONField(blank=True, default=list, verbose_name='Missing Skills')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='Recommendations')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Report Metadata')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_ats_reports', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Job ATS Report',
                'verbose_name_plural': 'Job ATS Reports',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
