# Generated by Django 5.2.15 on 2026-06-30 06:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('recorded_date', models.DateField(auto_now_add=True, unique=True, verbose_name='Recorded Date')),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('uploaded_resumes', models.IntegerField(default=0)),
                ('generated_portfolios', models.IntegerField(default=0)),
                ('generated_cover_letters', models.IntegerField(default=0)),
                ('average_ats_score', models.FloatField(default=0.0)),
                ('average_career_score', models.FloatField(default=0.0)),
                ('average_completion_percentage', models.FloatField(default=0.0)),
                ('storage_consumption', models.BigIntegerField(default=0, help_text='Total resume storage used in bytes')),
                ('ai_requests', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Admin Metrics',
                'verbose_name_plural': 'Admin Metrics Snapshots',
                'ordering': ['-recorded_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('storage_used', models.BigIntegerField(default=0)),
                ('storage_total', models.BigIntegerField(default=0)),
                ('database_status', models.CharField(default='healthy', max_length=50)),
                ('ai_service_status', models.CharField(default='healthy', max_length=50)),
                ('queue_status', models.CharField(default='healthy', max_length=50)),
                ('background_jobs_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'System Health Log',
                'verbose_name_plural': 'System Health Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('month', models.DateField(unique=True)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('growth_rate', models.FloatField(default=0.0, help_text='Percentage growth month-over-month')),
                ('retention_rate', models.FloatField(default=0.0, help_text='Percentage active retention rate')),
            ],
            options={
                'verbose_name': 'User Statistic',
                'verbose_name_plural': 'User Statistics',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Admin User')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_audit_targets', to=settings.AUTH_USER_MODEL, verbose_name='Target User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndustryStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.CharField(choices=[('role', 'Job Role'), ('skill', 'Skill'), ('certification', 'Certification'), ('technology', 'Technology'), ('industry', 'Industry')], db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('count', models.IntegerField(default=1)),
                ('trend_score', models.FloatField(default=0.0, help_text='Growth rate or importance weight')),
            ],
            options={
                'verbose_name': 'Industry Statistic',
                'verbose_name_plural': 'Industry Statistics',
                'ordering': ['-count'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UsageAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('event_type', models.CharField(choices=[('api_call', 'API Call'), ('ai_parse', 'AI Parse'), ('ats_score', 'ATS Score'), ('career_analysis', 'Career Analysis'), ('portfolio_gen', 'Portfolio Generation')], default='api_call', max_length=50)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('status_code', models.IntegerField(default=200)),
                ('processing_time', models.FloatField(default=0.0, help_text='Duration in seconds')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Usage Analytics Log',
                'verbose_name_plural': 'Usage Analytics Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='admin_intel_event_t_5d2ee2_idx'), models.Index(fields=['user', 'event_type'], name='admin_intel_user_id_458b1a_idx')],
            },
        ),
    ]
