# Generated by Django 5.2.15 on 2026-07-07 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0016_copilotaction_copilotconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeReputation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('score', models.IntegerField(verbose_name='Reputation Score')),
                ('tier', models.CharField(max_length=50, verbose_name='Reputation Tier')),
                ('career_score', models.IntegerField(verbose_name='Career Score')),
                ('growth_score', models.IntegerField(verbose_name='Growth Score')),
                ('market_score', models.IntegerField(verbose_name='Market Score')),
                ('details_json', models.JSONField(blank=True, default=dict, verbose_name='Full Details JSON')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputations', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Resume Reputation',
                'verbose_name_plural': 'Resume Reputations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('badge', models.CharField(max_length=100, verbose_name='Badge Name')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Earned At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='resumes.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['-earned_at'],
                'abstract': False,
                'unique_together': {('resume', 'badge')},
            },
        ),
    ]
